server:
    port: 8070

spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        url: jdbc:mysql://101.43.161.75:3306/wxp?useUnicode=true&characterEncodeing=UTF-8&severTimezone=Asia/Shanghai
        driver-class-name: com.mysql.jdbc.Driver
        username: wxp
        password: 123456
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xgs.pojo
