server:
  port: 8070

spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/wxp?useUnicode=true&characterEncodeing=UTF-8&severTimezone=Asia/Shanghai
      driver-class-name: com.mysql.jdbc.Driver
      username: wxp
      password: 123456

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xgs.pojo


